#!/bin/bash
list="NOTIFICATION_GENERIC,NOTIFICATION_FLAG,NOTIFICATION_LIGHTHOUSE,GENERIC_EMAIL,GENERIC_SMS,GENERIC_WARNING,GENERIC_CONFIRMATION,GENERIC_QUESTION,PARTLY_CLOUDY,CLOUDY_DAY,LIGHT_SNOW,LIGHT_RAIN,HEAVY_RAIN,HEAVY_SNOW,TIMELINE_WEATHER,TIMELINE_SUN,RAINING_AND_SNOWING,TIMELINE_MISSED_CALL,TIMELINE_CALENDAR,TIMELINE_SPORTS,TIMELINE_BASEBALL,AMERICAN_FOOTBALL,BASKETBALL,CRICKET_GAME,SOCCER_GAME,HOCKEY_GAME,RESULT_DISMISSED,RESULT_DELETED,RESULT_MUTE,RESULT_SENT,RESULT_FAILED,STOCKS_EVENT,MUSIC_EVENT,BIRTHDAY_EVENT,NEWS_EVENT,SCHEDULED_EVENT,MOVIE_EVENT,NO_EVENTS,PAY_BILL,HOTEL_RESERVATION,TIDE_IS_HIGH,INCOMING_PHONE_CALL,DURING_PHONE_CALL,DURING_PHONE_CALL_CENTERED,DISMISSED_PHONE_CALL,CHECK_INTERNET_CONNECTION,GLUCOSE_MONITOR,ALARM_CLOCK,CAR_RENTAL,DINNER_RESERVATION,RADIO_SHOW,AUDIO_CASSETTE,SCHEDULED_FLIGHT,REACHED_FITNESS_GOAL,DAY_SEPARATOR,WATCH_DISCONNECTED,TV_SHOW,LOCATION,SETTINGS"

oldifs="$IFS"
while read -d, -r line; do

  echo "GET: $line"
  url="https://developer.rebble.io/developer.pebble.com/assets/images/guides/timeline/$line.svg"
  wget $url

done <<< "$list"
IFS=$oldifs
